Add summary to step run
tox-dev/tox-gh pull request #63
Opened 2023-06-06 01:07 UTC by lengau

This writes a brief summary (one line per environment) to the GitHub run summary

2023-06-06 01:52 UTC, gaborbernat requested changes
Test for negative_squared_cross_mark please

2023-06-06 01:52 UTC, gaborbernat commented on src/tox_gh/plugin.py
> +    with open(GITHUB_STEP_SUMMARY, "a+") as f:
use pathlib.open instead

2023-06-06 01:53 UTC, gaborbernat commented on src/tox_gh/plugin.py
> +    with open(GITHUB_STEP_SUMMARY, "a+") as f:
also no single letter variables please

2023-06-08 03:05 UTC, lengau commented on src/tox_gh/plugin.py
> +    with open(GITHUB_STEP_SUMMARY, "a+") as f:
All 3 fixed :-)

2023-06-08 03:25 UTC, gaborbernat approved these changes

2023-06-08 06:18 UTC, gaborbernat commented
CI failing

2023-06-11 04:04 UTC, merged

2023-06-11 16:53 UTC, lengau commented
Thanks for your help and patience @gaborbernat !